export const productivities = {
    "Chop And DropChop and Drop": 300,
    "Chop And DropChange Sleeve": 150,
    "Chop And DropPaste UPC": 280,
    "House MadeHouse Made": 60,
    "Vases CDHouse Made": 40,
    "Vases CDVases CD": 60,
    "E. CommerceE. Commerce": 130,
    "Chop And DropAdd 1 Stem": 250,
    "Chop And DropQuality Check": 190,
    "Paste LabelRepack": 80,
    "Paste LabelChange Sleeve": 60,
    "Paste LabelPaste Label": 1000,
    "Chop And DropPaste UPC\\Q.Check": 100,
    "Chop And DropChange Sleeve\\Q.Check": 60,
    "Chop And DropAdd Food": 200,
    "Paste LabelHouse Made": 10,
    "Paste LabelPaste UPC": 20,
    "House MadeSample": 50,
    "Chop And DropRepair": 190,
    "Paste LabelQuality check": 60,
    "House MadeArrangements": 120,
    "Vases CDAdd one stem": 80,
    "Vases CDQuality Check.": 70,
    "Repack repack/ChangeSleeve ": 40,
    "Paste LabelChange sleeve/Quality check": 25,
    "House MadeQuality Check": 45,
    "RepackRepack/Paste UPC": 50,
    "E. CommerceE. House made": 80,
}